### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by felipehcoutinho** [gussow/seeker#2]
Hi there. First of all, congratulations on building this tool! It is certainly useful and very much necessary and the benchmarking data looks great. 

I am running the python version and I was wondering if you would be willing to introduce an option to use multiple threads. I want to process a large dataset (about 1.6M sequences with Seeker) and was hoping to speed it up somehow.

Cheers,

F

**Comment by gussow** [comment]
Hi, happy that you've found the tool useful. We are happy to consider adding a multithreading option, though it may take us some time (if you'd like, feel free to implement one and submit a PR). In the interim, would you mind sharing a few more details, so I can get an idea of the data you're working with? Basically: 
* 1.6M sequences roughly of what lengths? 
* What type of hardware are you using?
* What command / code are you using to process the dataset? 
* How long does it seem to be taking?

This will help give us an idea of some of the use cases for Seeker, and we may be able to help you speed things up.

**Comment by felipehcoutinho** [comment]
My full set of sequences has the following characteristics:
> File: Genomes.fasta
> Contigs: 1604013
> Bases: 24641168274
> N50: 20911

My hardware specs are:
> Architecture:          x86_64
> CPU op-mode(s):        32-bit, 64-bit
> Byte Order:            Little Endian
> CPU(s):                144
> On-line CPU(s) list:   0-143
> Thread(s) per core:    2
> Core(s) per socket:    18
> Socket(s):             4
> NUMA node(s):          4
> Vendor ID:             GenuineIntel
> CPU family:            6
> Model:                 85
> Model name:            Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
> Stepping:              4
> CPU MHz:               1000.108
> CPU max MHz:           2301,0000
> CPU min MHz:           1000,0000
> BogoMIPS:              4602.36
> Virtualization:        VT-x
> L1d cache:             32K
> L1i cache:             32K
> L2 cache:              1024K
> L3 cache:              25344K
> NUMA node0 CPU(s):     0-17,72-89
> NUMA node1 CPU(s):     18-35,90-107
> NUMA node2 CPU(s):     36-53,108-125
> NUMA node3 CPU(s):     54-71,126-143


As a trial run I used only a subset of my sequences. With the following characteristics:
> File: Mixed_Set_Genomes.fasta
> Contigs: 32479
> Bases: 721113846
> N50: 31057

I ran:
`time predict-metagenome Mixed_Set_Genomes.fasta > Seeker_Results_MixedSet_Genomes.tsv`

The output of time was:

> real    123m42.839s
> user    197m36.819s
> sys     33m48.720s

**Comment by gussow** [comment]
Thanks for the information! This helps give us an idea of the type of data people are working with. Indeed, it looks like your data would benefit from parallelization. Hopefully we will be able to implement this soon, but until then I’d recommend splitting your Fasta and manually running a few prediction instances in parallel, you should be able to get it to finish in a workable amount of time. Good luck!
