### ISSUE TITLE
stuck on reading sequence

### ISSUE THREAD

**Issue by SDquest** [gussow/seeker#4]
Hi, I installed seeker through conda and it showed that the installation is successful. But when I run command "predict-metagenomic input.fasta", it always stuck on reading sequence and no error reports. Do you know what's the problem? 

I also tried installing seeker by "pip install seeker" and use the example input "PGE.txt" from seeker. The same issue appears all the time. Could you please help check. Many thanks!

**Comment by gussow** [comment]
Hi,
 
Thanks for you report. A couple of clarification questions - can you try running it on a smaller file, for example just using the first sequence (MH356729.1) in PGE.txt?
 
Also, is anything printed to the screen when you run the command?

**Comment by SDquest** [comment]
Hi,

Thanks for your response. It fixed now. Thank you : )

**Comment by gussow** [comment]
Excellent, no problem!
