### ISSUE TITLE
Error when training the model

### ISSUE THREAD

**Issue by zhang-HZAU** [gussow/seeker#6]
Hello, all
    I have configured tesorflow 2.0.0 on the GPU node, and now I want to train the model according to your prompts. When I run the code "**python train_model.py --bacteria sample_bacteria_trainig.txt --phage sample_phage_training.txt --out sample_model.h5**", the following error appears: "File "train_model.py", line 7
     <!DOCTYPE html>
     ^
SyntaxError: invalid syntax", what should I do to get model.h5 correctly.
Thank you for your answers!
JIE

**Comment by gussow** [comment]
Hello,

This indicates there is an error in how the Python is written. If you made a change on line 7 in train_model.py, that may be causing it.

Hope that helps!

Ayal

**Comment by zhang-HZAU** [comment]
Hello ,
Sorry, I don't understand what you mean. In fact, I downloaded the source code and data directly from the github repository. I did not make any changes and reported the above error when I ran it directly. My Python version is 3.6.2, and TensorFlow is GPU version 2.0.0. Based on this platform, the prediction examples given in your github repository can be successfully reproduced. Now I want to know how to modify to reproduce the content of your model training.Thank you.
Looking forward to your answer.
jie,

**Comment by zhang-HZAU** [comment]
Hello ,
I found a small error here. The command given on github: "python train_model.py --bacteria sample_bacteria_trainig.txt --phage sample_phage_training.txt --out sample_model.h5",The file name of the first input file is wrong, "*.trainig.txt" should be changed to "*.training.txt", that is, "n" is missing.
In addition, when I run the script to train the model, an error was reported: "python: symbol lookup error: /my_path/libmkl_intel_thread.so: undefined symbol: omp_get_num_procs". What should I do? Openmp is used to run the script?
Thank you for your patient guidance.
jie,

**Comment by gussow** [comment]
Thank you for catching that error, we have corrected it!

Unfortunately, the other error you detailed is not something that is in our ability to debug. It appears to be related to the version or location that an external package that Seeker relies on is installed, and googling the error did not give us a clear resolution.
