### ISSUE TITLE
Something about LSTM model

### ISSUE THREAD

**Issue by zhang-HZAU** [gussow/seeker#7]
Hello,

Your team's use of the LSTM network to classify bacteria and phages is really an amazing innovation. Now I am very interested in your contribution. I found that the script you provided to train the model in the github project ended up with a "matlab" model. I have some questions:

① I know that "seeker" encodes bases in two ways. The "python" model converts bases into integer numbers, and "matlab" uses "one-hot" to encode bases. These two encoding methods are designed to What is it to compare the final prediction results in these two cases?
②I found that the fasta input data used to train the model on your github is a sequence with only one line of 1000bp under one ID. In practical applications, it is often a sequence of multiple lines under one ID. Can you provide a script for data preprocessing and training to get the "python" model?

Thank you in advance for your help. Looking forward to your answer~

Jay.

**Comment by gussow** [comment]
Happy our work has been useful to you. I didn't follow your first question. For you second question, there are multiple command line tools that allow splitting a Fasta into sequences of equal size. We also do have a function that does this in the included package, though you will have to write the code that writes the split sequences to a file.
